### ISSUE TITLE
Incorrect iOS icons when building for capacitor.

### ISSUE THREAD

**Issue by gdesoto** [quasarframework/app-extension-icon-genie#100]
I think I narrowed the issue to icon-genie > lib/settings.js.

When preparing to distribute app in xcode, the following warning were thrown:
1. The 83.5@2x file is 165x165. It should be 167x167.
2. Ambiguous icon AppIcon-512x512@2x.png.

I was able to remove the warnings by:
1. Copying the 83.5@2x icon generated for Cordova into the iOS assets folder generated for Capacitor
2. Deleting AppIcon-512x512@2x file from the iOS assets folder.

```
ios_icon_83_5_2x: {
  platform: 'ios',
  background: true,
  folder: 'ios/App/App/Assets.xcassets/AppIcon.appiconset',
  prefix: 'AppIcon-83.5x83.5@2x',
  infix: false,
  suffix: '.png',
  sizes: [
    165   // Should be 167
  ]
},
ios_icon_512_2x_1: {
  platform: 'ios',
  background: false,
  folder: 'ios/App/App/Assets.xcassets/AppIcon.appiconset',
  prefix: 'AppIcon-512@2x',   // This one is okay
  infix: false,
  suffix: '.png',
  sizes: [
    1024
  ]
},
ios_icon_512_2x_2: {
  platform: 'ios',
  background: false,
  folder: 'ios/App/App/Assets.xcassets/AppIcon.appiconset',
  prefix: 'AppIcon-512x512@2x',   // Should not exist?
  infix: false,
  suffix: '.png',
  sizes: [
    1024
  ]
},
```

Let me know if I'm missing something.

**Comment by rstoenescu** [comment]
Hi,

You are perfectly right with both issues above.
Updated and it will be available in IconGenie v1.1.3.
