### ISSUE TITLE
yarn update from 1.01 to 1.0.2 results in errors [windows]

### ISSUE THREAD

**Issue by ontwikkelfabriek** [quasarframework/app-extension-icon-genie#92]
I updated a perfect running genie from 1.0.1 to 1.0.2 with yarn on a Windows 10 machine.

It results in the following mess:

[genie-error-log.txt](https://github.com/quasarframework/app-extension-icon-genie/files/3604943/genie-error-log.txt)

btw: when I go back to version 1.0.1 everything works again...

**Comment by hawkeye64** [comment]
Thanks for reporting. The only thing I see in your attached file is this:
```
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\playground\mybetaquasar\node_modules\sharp\build\binding.sln]
```

**Comment by ontwikkelfabriek** [comment]
I will take a look at that. But why is this no problem with version 1.0.1 ?

**Comment by hawkeye64** [comment]
@ontwikkelfabriek No idea as I don't have Windows :(

**Comment by ontwikkelfabriek** [comment]
I solved this error by switching Node from v11.x to  v10.13.0 (LTS).
